apiVersion: batch/v1
kind: Job
metadata:
  name: dpa-api-migrate
  namespace: dpa
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-db
          image: postgres:14
          command:
            - sh
            - -c
            - |
              until pg_isready -h "$DPA_DB_HOST" -U "$DPA_DB_USER" -p 5432; do
                echo "waiting for databaseâ€¦";
                sleep 2;
              done
          env:
            - name: DPA_DB_HOST
              value: postgresql.dpa.svc.cluster.local          
            - name: DPA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: DPA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username  
      containers:
        - name: migrate
          image: dpa-guard-api:dev
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DPA_DB_HOST
              value: postgresql.dpa.svc.cluster.local          
            - name: DPA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: DPA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
          
