apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dpa-api-secrets
  namespace: dpa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dpa-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DPA_DB_USER
      remoteRef:
        key: dpa/db
        property: username
    - secretKey: DPA_DB_PASSWORD
      remoteRef:
        key: dpa/db
        property: password
    - secretKey: DPA_MINIO_USER
      remoteRef:
        key: dpa/minio
        property: rootUser
    - secretKey: DPA_MINIO_PASSWORD
      remoteRef:
        key: dpa/minio
        property: rootPassword
