apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-creds
  namespace: dpa
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio-creds
    creationPolicy: Owner
  data:
    - secretKeyRef:
        key: rootUser
      remoteRef:
        key: dpa/minio
        property: rootUser
    - secretKeyRef:
        key: rootPassword
      remoteRef:
        key: dpa/minio
        property: rootPassword