apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: dpa
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dpa/db
        property: username
    - secretKey: password
      remoteRef:
        key: dpa/db
        property: password